C:\Users\GiovanniPio\AppData\Local\Microsoft\WindowsApps\python3.9.exe "C:\Program Files\JetBrains\PyCharm Community Edition 2020.3.3\plugins\python-ce\helpers\pydev\pydevconsole.py" --mode=client --port=65312
import sys; print('Python %s on %s' % (sys.version, sys.platform))
sys.path.extend(['C:\\Users\\GiovanniPio\\Desktop\\tesi\\lcquad\\scripts', 'C:/Users/GiovanniPio/Desktop/tesi/lcquad/scripts'])
PyDev console: starting.
Python 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] on win32
import itertools
first_list = []
second_list = ["something", "another_thing"]
third_list = ["jeje", "lala", "cc"]
list_of_lists = [first_list, second_list, third_list]
list_of_lists
[[], ['something', 'another_thing'], ['jeje', 'lala', 'cc']]
itertools.product(*list_of_lists)
<itertools.product object at 0x0000014EF36681C0>
for tuple_to_print in itertools.product(*list_of_list):
    print(tuple_to_print)
    
Traceback (most recent call last):
  File "<input>", line 1, in <module>
NameError: name 'list_of_list' is not defined
for tuple_to_print in itertools.product(*list_of_lists):
    print(tuple_to_print)
    
list_of_lists[0].append("jaja")
for tuple_to_print in itertools.product(*list_of_lists):
    print(tuple_to_print)
    
('jaja', 'something', 'jeje')
('jaja', 'something', 'lala')
('jaja', 'something', 'cc')
('jaja', 'another_thing', 'jeje')
('jaja', 'another_thing', 'lala')
('jaja', 'another_thing', 'cc')
list_of_lists[3] = [["baba", "jaga"]]
Traceback (most recent call last):
  File "<input>", line 1, in <module>
IndexError: list assignment index out of range
list_of_lists[2] = [["baba", "jaga"]]
for tuple_to_print in itertools.product(*list_of_lists):
    print(tuple_to_print)
    
('jaja', 'something', ['baba', 'jaga'])
('jaja', 'another_thing', ['baba', 'jaga'])
dict_1 = {"baba":{"var1":["gangshit", "noncredo", "bestemmio", "ilcredo"]}, "jaga":{"var2":["sonoil", "ceo", "bestemmio il cielo"]}, "gaga":{}}
dict_1
{'baba': {'var1': ['gangshit', 'noncredo', 'bestemmio', 'ilcredo']}, 'jaga': {'var2': ['sonoil', 'ceo', 'bestemmio il cielo']}, 'gaga': {}}
list_of_lists = []
for var_to_use in dict_1:
    for list_to_consider in dict_1.get(var_to_use).key():
        list_of_lists.append(list_to_consider)
        
Traceback (most recent call last):
  File "<input>", line 2, in <module>
AttributeError: 'dict' object has no attribute 'key'
for var_to_use in dict_1:
    for list_to_consider in dict_1.get(var_to_use).keys():
        list_of_lists.append(list_to_consider)
        
list_of_lists
['var1', 'var2']
list_of_lists = []
for var_to_use in dict_1:
    for list_to_consider in dict_1.get(var_to_use).keys():
        list_of_lists.append(dict_1.get(var_to_use).get(list_to_consider))
        
list_of_lists
[['gangshit', 'noncredo', 'bestemmio', 'ilcredo'], ['sonoil', 'ceo', 'bestemmio il cielo']]
combinations = []
for tuple_to_consider in itertools.product(*list_of_lists):
    combinations.append(tuple_to_consider)
    
combinations
[('gangshit', 'sonoil'), ('gangshit', 'ceo'), ('gangshit', 'bestemmio il cielo'), ('noncredo', 'sonoil'), ('noncredo', 'ceo'), ('noncredo', 'bestemmio il cielo'), ('bestemmio', 'sonoil'), ('bestemmio', 'ceo'), ('bestemmio', 'bestemmio il cielo'), ('ilcredo', 'sonoil'), ('ilcredo', 'ceo'), ('ilcredo', 'bestemmio il cielo')]
list_of_dicts = []
for current_combination in combinations:
    temp_dict = {}
    i = 0
    for var_to_consider in dict_1:
       temp_dict.update({var_to_consider:current_combination[i]})
       i += 1
    list_of_dicts.append(temp_dict)
Traceback (most recent call last):
  File "<input>", line 5, in <module>
IndexError: tuple index out of range
for current_combination in combinations:
    temp_dict = {}
    i = 0
    for var_to_consider in dict_1:
       temp_dict.update({var_to_consider:current_combination[i]})
       i += 1
    list_of_dicts.append(temp_dict)
Traceback (most recent call last):
  File "<input>", line 5, in <module>
IndexError: tuple index out of range
for current_combination in combinations:
    temp_dict = {}
    i = 0
    for var_to_consider in dict_1:
       if len(dict_1.get(var_to_consider)) > 0:
        temp_dict.update({var_to_consider:current_combination[i]})
        i += 1
    list_of_dicts.append(temp_dict)
list_of_dicts
[{'baba': 'gangshit', 'jaga': 'sonoil'}, {'baba': 'gangshit', 'jaga': 'ceo'}, {'baba': 'gangshit', 'jaga': 'bestemmio il cielo'}, {'baba': 'noncredo', 'jaga': 'sonoil'}, {'baba': 'noncredo', 'jaga': 'ceo'}, {'baba': 'noncredo', 'jaga': 'bestemmio il cielo'}, {'baba': 'bestemmio', 'jaga': 'sonoil'}, {'baba': 'bestemmio', 'jaga': 'ceo'}, {'baba': 'bestemmio', 'jaga': 'bestemmio il cielo'}, {'baba': 'ilcredo', 'jaga': 'sonoil'}, {'baba': 'ilcredo', 'jaga': 'ceo'}, {'baba': 'ilcredo', 'jaga': 'bestemmio il cielo'}]
def int_returning_function():
    return int
num = int_returning_function()("i")
Traceback (most recent call last):
  File "<input>", line 1, in <module>
ValueError: invalid literal for int() with base 10: 'i'
num = int_returning_function()("1")
num
1
import datetime
x = datetime.date(2021, 6, 17)
x
datetime.date(2021, 6, 17)
y = datetime.date(0, 1, 0)
Traceback (most recent call last):
  File "<input>", line 1, in <module>
ValueError: year 0 is out of range
y = datetime.date(2021, 1, 18)
x + y
Traceback (most recent call last):
  File "<input>", line 1, in <module>
TypeError: unsupported operand type(s) for +: 'datetime.date' and 'datetime.date'
date_1 = datetime.datetime.strptime("1980-06-17", "%y-%m-%d")
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1520.0_x64__qbz5n2kfra8p0\lib\_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1520.0_x64__qbz5n2kfra8p0\lib\_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data '1980-06-17' does not match format '%y-%m-%d'
date_1 = datetime.datetime.strptime("1980-6-17", "%y-%m-%d")
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1520.0_x64__qbz5n2kfra8p0\lib\_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1520.0_x64__qbz5n2kfra8p0\lib\_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data '1980-6-17' does not match format '%y-%m-%d'
date_1 = datetime.datetime.strptime("1980-6-17", "%Y-%m-%d")
date_1
datetime.datetime(1980, 6, 17, 0, 0)
date_1 = datetime.datetime.strptime("0-1-0", "%Y-%m-%d")
Traceback (most recent call last):
  File "<input>", line 1, in <module>
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1520.0_x64__qbz5n2kfra8p0\lib\_strptime.py", line 568, in _strptime_datetime
    tt, fraction, gmtoff_fraction = _strptime(data_string, format)
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.9_3.9.1520.0_x64__qbz5n2kfra8p0\lib\_strptime.py", line 349, in _strptime
    raise ValueError("time data %r does not match format %r" %
ValueError: time data '0-1-0' does not match format '%Y-%m-%d'
date_1 + datetime.timedelta(month = 1)
Traceback (most recent call last):
  File "<input>", line 1, in <module>
TypeError: 'month' is an invalid keyword argument for __new__()
date_1 + datetime.timedelta(months = 1)
Traceback (most recent call last):
  File "<input>", line 1, in <module>
TypeError: 'months' is an invalid keyword argument for __new__()
date_1 + datetime.timedelta(days = 30)
datetime.datetime(1980, 7, 17, 0, 0)
date_1 + datetime.timedelta(days = 365)
datetime.datetime(1981, 6, 17, 0, 0)
date_2 = datetime.datetime.strptime("1980-12-1", "%Y-%m-%d")
date_1 > date_2
False
datetime.timedelta(days=0)
datetime.timedelta(0)
date_1 < date_2
True
date_1.month
6
float("0.1")
0.1
date_3 = date_1 + datetime.timedelta(days = 365)
date_3
datetime.datetime(1981, 6, 17, 0, 0)
date_3.date()
datetime.date(1981, 6, 17)
